---
name: testing
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: current branch
    if: "!contains(github.event.pull_request.labels.*.name, 'breaking_change_allowed')"
      run: |
        echo "true"
    - name: current branch2
    if: "!contains(github.event.pull_request.labels.*.name, 'breaking_change_allowed')"
      run: |
        echo "false"
